# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a33ea1307c7a92279e076469c89c1f30db2e66beacfa625e1ed1d4755a0e91582db7c82f0056586dedbcf0f1e32b5410be6a5ce12d19bb389bf2a85ec84d23e

test:
  secret_key_base: b9086ea0a1b034fca8696c2138f807299e34296d560b6bfb0be63406b5a006a9718775656c03419532107d8a2886e069b2f48e59fb3b93386109374d6d4974d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
